# -*- coding: utf-8 -*-
"""v1.6 自检：RPG Maker 界面文本（System.json / plugins.js / 插件源码）。

覆盖三件事：
1. terms 回填路径修复（此前 KeyError 被静默吞掉）
2. System.json 的 messages / armorTypes / gameTitle 等此前未提取的字段
3. plugins.js 嵌套 JSON 字符串下钻 + 插件源码字面量
"""
from __future__ import annotations

import json
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from gametl.core.models import EngineType, Project, TextKind, TextUnit  # noqa: E402
from gametl.extractors.rpgmaker import RPGMakerExtractor  # noqa: E402

PASS = 0
FAIL = 0
FAILS: list[str] = []


def rec(cond, name: str) -> None:
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"  [OK] {name}")
    else:
        FAIL += 1
        FAILS.append(name)
        print(f"  [!!] {name}")


SYS = {
    "gameTitle": "テストゲーム 製品版",
    "currencyUnit": "Ｇ",
    "armorTypes": ["", "軽装", "重装"],
    "weaponTypes": ["", "短剣"],
    "skillTypes": ["", "魔法"],
    "elements": ["", "物理"],
    "terms": {
        "basic": ["レベル", "ＨＰ"],
        "commands": ["戦う", None, "逃げる", "アイテム"],
        "params": ["最大ＨＰ"],
        "messages": {
            "actionFailure": "戦闘に失敗した",
            "actorDamage": "%1 は %2 のダメージを受けた",
            "victory": "",
        },
    },
}

PLUGINS_JS = (
    "// Generated by RPG Maker.\n"
    "// Do not edit this file directly.\n"
    "var $plugins =\n"
    "[\n"
    '{"name":"TestMenu","status":true,"description":"d","parameters":'
    '{"---General---":"","baseItems":"[{\\"name\\":\\"サブステータス\\",'
    '\\"command\\":\\"x\\"}]","Speed":{"最遅":-2,"標準":0},'
    '"Path":"img/pictures/a.png","Flag":"true","Count":"12"}},\n'
    '{"name":"Other","status":true,"description":"d","parameters":{}}\n'
    "];\n"
)

PLUGIN_SRC = (
    "// テスト用プラグイン\n"
    "var a = 'クエスト確認';\n"
    "var b = \"customstatus\";\n"
    "var c = 'img/pictures/a.png';\n"
    "var d = '回想モード';\n"
    "var e = 'true';\n"
    "var f = 'レベル';\n"
)


def build_tree(base: Path) -> None:
    (base / "www" / "data").mkdir(parents=True, exist_ok=True)
    (base / "www" / "js" / "plugins").mkdir(parents=True, exist_ok=True)
    (base / "www" / "data" / "System.json").write_text(
        json.dumps(SYS, ensure_ascii=False), encoding="utf-8")
    (base / "www" / "js" / "plugins.js").write_text(PLUGINS_JS, encoding="utf-8")
    (base / "www" / "js" / "plugins" / "TestPlugin.js").write_text(
        PLUGIN_SRC, encoding="utf-8")


def main() -> int:
    print("=" * 62)
    print("v1.6 自检：RPG Maker 界面文本")
    print("=" * 62)
    tmp = Path(tempfile.mkdtemp(prefix="gametl_v16_"))
    try:
        game = tmp / "game"
        build_tree(game)
        ex = RPGMakerExtractor(game)

        # ---------- 1. 提取 ----------
        print("\n[1] 提取范围")
        units = ex.extract()
        by_file: dict[str, list[TextUnit]] = {}
        for u in units:
            by_file.setdefault(u.source_file, []).append(u)
        sys_units = by_file.get("www/data/System.json", [])
        pj_units = by_file.get("www/js/plugins.js", [])
        ps_units = by_file.get("www/js/plugins/TestPlugin.js", [])

        rec(len(sys_units) > 0, "System.json 有提取结果")
        rec(len(pj_units) > 0, "plugins.js 有提取结果")
        rec(len(ps_units) == 3, f"插件源码提取 3 条（实际 {len(ps_units)}）")

        locs = {json.dumps(u.location, sort_keys=True, ensure_ascii=False): u
                for u in sys_units}
        # terms 三组
        rec(any(u.location.get("group") == "basic" and u.location.get("index") == 0
                for u in sys_units), "terms.basic[0] 提取到")
        rec(any(u.location.get("group") == "commands" and u.location.get("index") == 3
                for u in sys_units), "terms.commands[3] 提取到")
        # ★ messages 是对象 —— 旧版按 list 处理会整段漏掉
        rec(any(u.location.get("group") == "messages"
                and u.location.get("key") == "actionFailure" for u in sys_units),
            "terms.messages（对象型）提取到")
        rec(not any(u.location.get("group") == "messages"
                    and u.location.get("key") == "victory" for u in sys_units),
            "空字符串的 messages 被跳过")
        # 顶层字段
        rec(any(u.location.get("top") == "armorTypes" and u.location.get("index") == 1
                for u in sys_units), "armorTypes[1] 提取到")
        rec(any(u.location.get("top") == "weaponTypes" for u in sys_units),
            "weaponTypes 提取到")
        rec(any(u.location.get("top") == "skillTypes" for u in sys_units),
            "skillTypes 提取到")
        rec(any(u.location.get("top") == "elements" for u in sys_units),
            "elements 提取到")
        rec(any(u.location.get("top") == "gameTitle" for u in sys_units),
            "gameTitle 提取到")
        rec(any(u.location.get("top") == "currencyUnit" for u in sys_units),
            "currencyUnit 提取到")

        # plugins.js：嵌套 JSON 必须下钻
        rec(any(u.location.get("param") == "baseItems"
                and u.location.get("path") == [0, "name"]
                for u in pj_units), "嵌套 JSON 字符串里的 name 下钻到")
        rec(any(u.location.get("param") == "Speed"
                and u.location.get("path") == ["最遅"]
                for u in pj_units), "以真对象形式给出的日文键下钻到")
        # 机器串必须被挡下
        rec(not any(u.location.get("param") == "Path" for u in pj_units),
            "图片路径未被当成文本")
        rec(not any(u.location.get("param") == "Flag" for u in pj_units),
            "布尔值未被当成文本")
        rec(not any(u.location.get("param") == "Count" for u in pj_units),
            "数字字符串未被当成文本")
        rec(not any(u.location.get("param") == "---General---" for u in pj_units),
            "插件分组标题未被当成文本")

        # 插件源码：只留日文
        src_orig = {u.original for u in ps_units}
        rec("クエスト確認" in src_orig, "源码：クエスト確認 提取到")
        rec("回想モード" in src_orig, "源码：回想モード 提取到")
        rec("レベル" in src_orig, "源码：纯汉字界面词 提取到")
        rec("customstatus" not in src_orig, "源码：英文标识符被挡下")
        rec("img/pictures/a.png" not in src_orig, "源码：路径被挡下")
        rec("true" not in src_orig, "源码：布尔字面量被挡下")

        # ---------- 2. 回填 ----------
        print("\n[2] 回填")
        tr = {
            "テストゲーム 製品版": "测试游戏 正式版",
            "Ｇ": "金币",
            "軽装": "轻装", "重装": "重装", "短剣": "短剑", "魔法": "魔法",
            "物理": "物理",
            "レベル": "等级", "ＨＰ": "HP", "戦う": "战斗", "逃げる": "逃跑",
            "アイテム": "物品", "最大ＨＰ": "最大HP",
            "戦闘に失敗した": "战斗失败了",
            "%1 は %2 のダメージを受けた": "%1 受到了 %2 点伤害",
            "サブステータス": "子状态",
            "最遅": "最慢", "標準": "标准",
            "クエスト確認": "任务确认", "回想モード": "回想模式",
        }
        for u in units:
            if u.original in tr:
                u.translated = tr[u.original]
        proj = Project(root=game, engine=EngineType.RPGMAKER_MV, units=units)

        out = tmp / "out"
        stats = ex.write_back(proj, out)
        rec(stats["files_written"] >= 3, f"回填写入文件数（{stats['files_written']}）")
        rec(set(stats["changed"]) >= {
            "www/data/System.json", "www/js/plugins.js",
            "www/js/plugins/TestPlugin.js"}, "changed 清单包含三个文件")

        ns = json.loads((out / "www/data/System.json").read_text(encoding="utf-8"))
        # ★ 核心回归：terms 必须真的写进去
        rec(ns["terms"]["basic"][0] == "等级", "terms.basic[0] 回填成功")
        rec(ns["terms"]["commands"][0] == "战斗", "terms.commands[0] 回填成功")
        rec(ns["terms"]["commands"][3] == "物品", "terms.commands[3] 回填成功")
        rec(ns["terms"]["params"][0] == "最大HP", "terms.params[0] 回填成功")
        rec(ns["terms"]["messages"]["actionFailure"] == "战斗失败了",
            "terms.messages（对象型）回填成功")
        rec(ns["terms"]["messages"]["actorDamage"] == "%1 受到了 %2 点伤害",
            "terms.messages 占位符 %1 %2 保留")
        rec(ns["terms"]["commands"][1] is None, "原 null 位置未被破坏")
        rec(ns["armorTypes"][1] == "轻装", "armorTypes 回填成功")
        rec(ns["weaponTypes"][1] == "短剑", "weaponTypes 回填成功")
        rec(ns["skillTypes"][1] == "魔法", "skillTypes 回填成功")
        rec(ns["elements"][1] == "物理", "elements 回填成功")
        rec(ns["gameTitle"] == "测试游戏 正式版", "gameTitle 回填成功")
        rec(ns["currencyUnit"] == "金币", "currencyUnit 回填成功")
        # 顶层没有多出杂键
        rec("basic" not in ns and "commands" not in ns,
            "没有往 System.json 顶层写出错误的键")

        pj_text = (out / "www/js/plugins.js").read_text(encoding="utf-8")
        rec(pj_text.startswith("// Generated by RPG Maker."),
            "plugins.js 头部注释保留")
        rec(pj_text.rstrip().endswith("];"), "plugins.js 以 ]; 结尾")
        pj = RPGMakerExtractor._read_plugins_js(out / "www/js/plugins.js")
        rec(pj is not None and len(pj) == 2, "回填后的 plugins.js 仍是合法 JSON")
        if pj:
            params = pj[0]["parameters"]
            nested = json.loads(params["baseItems"])
            rec(nested[0]["name"] == "子状态", "嵌套 JSON 里的界面词回填成功")
            rec(nested[0]["command"] == "x", "嵌套 JSON 的非文本字段未被改动")
            rec("最慢" in params["Speed"], "嵌套 JSON 的日文键回填成功")
            rec(params["Path"] == "img/pictures/a.png", "参数里的路径未被改动")
            rec(params["Flag"] == "true", "参数里的布尔未被改动")
            rec(pj[1]["name"] == "Other", "其它插件对象未被破坏")

        ps_text = (out / "www/js/plugins/TestPlugin.js").read_text(encoding="utf-8")
        rec("'任务确认'" in ps_text, "源码字面量回填成功")
        rec("'回想模式'" in ps_text, "源码第二处字面量回填成功")
        rec("'等级'" in ps_text, "源码汉字界面词回填成功")
        rec('"customstatus"' in ps_text, "源码英文标识符未被改动")
        rec("'img/pictures/a.png'" in ps_text, "源码路径未被改动")
        rec("var e = 'true';" in ps_text, "源码布尔未被改动")
        rec("// テスト用プラグイン" in ps_text, "源码注释未被改动")

        # ---------- 3. 按需写入 ----------
        print("\n[3] 按需写入（增量导出的前提）")
        out2 = tmp / "out2"
        stats2 = ex.write_back(proj, out2)
        rec(stats2["files_written"] == stats["files_written"],
            "重跑一次结果一致")
        out3 = tmp / "out3"
        shutil.copytree(out2, out3)
        before = {p: p.stat().st_mtime_ns for p in out3.rglob("*") if p.is_file()}
        stats3 = ex.write_back(proj, out3)
        after = {p: p.stat().st_mtime_ns for p in out3.rglob("*") if p.is_file()}
        rec(stats3["files_written"] == 0, "内容没变时不重写文件")
        rec(before == after, "文件 mtime 保持不变")

        # ---------- 4. 兼容旧 loc ----------
        print("\n[4] 兼容 v1.5 之前写下的工程条目")
        old = TextUnit(
            uid="x", source_file="www/data/System.json",
            location={"field": "terms", "group": "basic", "index": 1},
            original="ＨＰ", translated="HP", kind=TextKind.UI)
        out4 = tmp / "out4"
        ex.write_back(Project(root=game, engine=EngineType.RPGMAKER_MV,
                              units=[old]), out4)
        ns4 = json.loads((out4 / "www/data/System.json").read_text(encoding="utf-8"))
        rec(ns4["terms"]["basic"][1] == "HP", "旧格式 loc 仍能回填")

        # ---------- 5. 翻译包 ----------
        print("\n[5] 翻译包（免模型、跨设备、抗改名）")
        from gametl.core.package import (PackageError, export_package,  # noqa: E402
                                         export_file_patch, import_into,
                                         read_manifest)

        tmp2 = tmp / "pkg"
        tmp2.mkdir()
        pkg = tmp2 / "test.gtpkg"
        pres = export_package(proj, pkg)
        n_tr = sum(1 for u in units if u.translated)
        rec(pkg.is_file(), "翻译包已生成")
        rec(pres["units"] == n_tr, f"包内条数正确（{pres['units']}）")
        man = read_manifest(pkg)
        rec(man["engine"] == "rpgmaker_mv", "manifest 记录了引擎")
        rec(man["units_translated"] == n_tr, "manifest 条数与实际一致")
        rec(man["format"] == "gametl-translation-package", "manifest 格式标识正确")
        rec(pres["bytes"] < 200 * 1024, f"体积很小（{pres['bytes']} B）")

        # 模拟「别人的电脑」：换个盘、换个文件夹名叫别人的名字
        other = tmp2 / "别人的游戏目录_ver2"
        shutil.copytree(game, other)
        ex2 = RPGMakerExtractor(other)
        u2 = ex2.extract()
        rec(all(u.translated is None for u in u2), "对方工程一开始没有任何译文")
        p2 = Project(root=other, engine=EngineType.RPGMAKER_MV, units=u2)
        res2 = import_into(p2, pkg)
        rec(res2["by_uid"] == n_tr,
            f"目录改名换位置后 uid 依然全部命中（{res2['by_uid']}/{n_tr}）")
        rec(res2["missed"] == 0, "没有漏下的条目")
        rec(sum(1 for u in p2.units if u.translated) == res2["by_uid"],
            "译文已写进对方工程")

        # 模拟「版本不同」：文件路径变了 → uid 全部失配，靠原文兜底
        u3 = ex2.extract()
        for u in u3:
            u.source_file = "www/data2/" + u.source_file.split("/")[-1]
            u.uid = TextUnit.make_uid(u.source_file, u.location, u.original)
        p3 = Project(root=other, engine=EngineType.RPGMAKER_MV, units=u3)
        res3 = import_into(p3, pkg)
        rec(res3["by_uid"] == 0, "换了目录结构后 uid 全部失配（符合预期）")
        rec(res3["by_memory"] == n_tr,
            f"按原文兜底救回 {res3['by_memory']}/{n_tr} 条")
        rec(res3["missed"] == 0, "兜底后没有漏下的条目")

        # 关掉兜底
        u4 = ex2.extract()
        for u in u4:
            u.source_file = "www/data2/" + u.source_file.split("/")[-1]
            u.uid = TextUnit.make_uid(u.source_file, u.location, u.original)
        p4 = Project(root=other, engine=EngineType.RPGMAKER_MV, units=u4)
        res4 = import_into(p4, pkg, use_memory=False)
        rec(res4["by_memory"] == 0 and res4["missed"] == n_tr,
            "关掉兜底后不再按原文复用")

        # 坏包要拒绝，而不是静默当成空包
        bad = tmp2 / "bad.gtpkg"
        bad.write_bytes(b"not a zip at all")
        try:
            read_manifest(bad)
            rec(False, "损坏的包应当报错")
        except PackageError:
            rec(True, "损坏的包被正确拒绝")

        # 文件补丁（只含汉化后的文件，供对方直接覆盖）
        patch_dir = tmp2 / "patch"
        fres = export_file_patch(out, patch_dir, "测试游戏",
                                 changed_only=["www/data/System.json"])
        rec(fres["files"] == 1, "文件补丁按清单只导出 1 个文件")
        rec((patch_dir / "www/data/System.json").is_file(),
            "文件补丁保持了原目录结构")
        rec((patch_dir / "安装说明.txt").is_file(), "文件补丁附带安装说明")
        fres2 = export_file_patch(out, tmp2 / "patch2", "测试游戏")
        rec(fres2["files"] == 3, f"全量文件补丁导出 3 个文件（实际 {fres2['files']}）")

        # ---------- 6. 端到端：导入翻译包后完全不碰模型 ----------
        print("\n[6] 端到端：导入翻译包后不碰模型")
        from gametl.auto import AutoConfig, AutoPipeline  # noqa: E402
        mock = ROOT / "gametl" / "examples" / "mock_rpgmaker_example"
        if not mock.is_dir():
            rec(False, "找不到 mock 游戏目录")
        else:
            exm = RPGMakerExtractor(mock)
            um = exm.extract()
            for u in um:
                u.translated = "译" + u.original[:6]
            export_package(Project(root=mock, engine=EngineType.RPGMAKER_MV,
                                   units=um), tmp2 / "mock.gtpkg")

            logs: list[str] = []
            cfg2 = AutoConfig(
                game_dir=mock,
                out_dir=tmp2 / "mockout",
                work_root=tmp2 / "mockwork",
                import_package=tmp2 / "mock.gtpkg",
                # 故意指向一个不存在的服务：只要流程碰模型，这里就会失败
                host="http://127.0.0.1:1",
                pack_output=False,
            )
            res6 = AutoPipeline(cfg2, on_log=logs.append).run()
            rec(res6.success, f"流程跑通（到 {res6.stage_reached}）")
            rec(res6.package_imported == len(um),
                f"包内 {len(um)} 条全部导入（实际 {res6.package_imported}）")
            rec(res6.translated_units == 0, "没有调用模型翻译任何条目")
            rec(any("跳过翻译阶段" in m for m in logs), "翻译阶段被跳过")
            wb = tmp2 / "mockwork" / "_work" / "translated"
            rec(wb.is_dir() and any(wb.rglob("*")), "回填产物已生成")
            if (wb / "www/data/System.json").is_file():
                nsx = json.loads((wb / "www/data/System.json")
                                 .read_text(encoding="utf-8"))
                rec(nsx["terms"]["basic"][0].startswith("译"),
                    "回填产物里的菜单术语已是译文")

        # ---------- 7. 增量导出 ----------
        print("\n[7] 增量导出（改了译文不必重拷整个游戏）")
        from gametl.auto import export_full_game  # noqa: E402
        g7 = tmp / "g7"
        (g7 / "www" / "data").mkdir(parents=True)
        (g7 / "www" / "data" / "a.json").write_text("{}", encoding="utf-8")
        (g7 / "readme.txt").write_text("hi", encoding="utf-8")
        (g7 / "big.bin").write_bytes(b"x" * 4096)
        wr7 = tmp / "w7"
        tr7 = wr7 / "_work" / "translated" / "www" / "data"
        tr7.mkdir(parents=True)
        (tr7 / "a.json").write_text('{"t":1}', encoding="utf-8")
        d7 = tmp / "out7"

        r1 = export_full_game(g7, wr7, d7)
        rec(r1["files"] == 3, f"首次导出复制 3 个文件（实际 {r1['files']}）")
        rec(r1["skipped"] == 0, "首次没有可跳过的")
        rec((d7 / ".gametl_export.json").is_file(), "写下了增量快照")
        rec((d7 / "www/data/a.json").read_text(encoding="utf-8") == '{"t":1}',
            "译文覆盖了同名的游戏原文件")

        r2 = export_full_game(g7, wr7, d7)
        rec(r2["files"] == 0, f"内容没变时一个都不拷（实际 {r2['files']}）")
        rec(r2["skipped"] == 3, f"3 个文件全部跳过（实际 {r2['skipped']}）")

        # 译文改一句（同时改长度，避免同秒同尺寸的歧义）→ 只有它要重拷
        (tr7 / "a.json").write_text('{"t":22222}', encoding="utf-8")
        r3 = export_full_game(g7, wr7, d7)
        rec(r3["files"] == 1, f"只重拷改动的那 1 个（实际 {r3['files']}）")
        rec(r3["skipped"] == 2, f"其余 2 个跳过（实际 {r3['skipped']}）")
        rec((d7 / "www/data/a.json").read_text(encoding="utf-8") == '{"t":22222}',
            "改动已落到成品")

        # 关掉增量就必须老老实实全拷
        r4 = export_full_game(g7, wr7, d7, incremental=False)
        rec(r4["files"] == 3 and r4["skipped"] == 0,
            "incremental=False 时强制全量")

        # 目标在游戏目录内部要拦住
        try:
            export_full_game(g7, wr7, g7 / "sub")
            rec(False, "应拒绝把成品导进游戏目录内部")
        except RuntimeError:
            rec(True, "拒绝把成品导进游戏目录内部")

    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print("\n" + "=" * 62)
    print(f"通过 {PASS} / {PASS + FAIL}")
    if FAILS:
        print("失败项：")
        for f in FAILS:
            print("  - " + f)
    print("=" * 62)
    return 1 if FAIL else 0


if __name__ == "__main__":
    raise SystemExit(main())
